apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template: # POD TEMPLATE: Defines the pod that will be created by the Deployment
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web-container
        # We put a dummy image here; GitHub Actions replaces this exact line dynamically!
        image: placeholder-image 
        ports:
        - containerPort: 80

---
apiVersion: v1 #
kind: Service # SERVICE DEFINITION: Exposes the Deployment to the internet via a LoadBalancer
metadata:
  name: webapp-loadbalancer # SERVICE NAME: webapp-loadbalancer
spec:
  type: LoadBalancer # SERVICE TYPE: LoadBalancer for EKS to provision an ELB
  selector:
    app: webapp # SELECTOR: Matches the label in the Deployment to route traffic to the correct pods
  ports: # PORTS: Defines the port mapping for the service
    - protocol: TCP
      port: 80 # SERVICE PORT: The port that the LoadBalancer listens on
      targetPort: 80 # TARGET PORT: The port on the container that receives traffic (must match containerPort in Deployment)