apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web-container
        # We put a dummy image here; GitHub Actions replaces this exact line dynamically!
        image: placeholder-image 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer
spec:
  type: LoadBalancer 
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80